// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrrwfelxiielfufdbazf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycndmZWx4aWllbGZ1ZmRiYXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTYxMzYsImV4cCI6MjA3NDQzMjEzNn0.yf2ONLkSo6drrgdtpla2e5dg4ve7AvyLMOoftub0mo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});